version: '2'

services:
  etcd:
    image: docker.io/bitnami/etcd:3
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-server:2379
    volumes:
      - etcd_data:/bitnami/etcd
    ports:
      - 2379:2379
      - 2380:2380
volumes:
  etcd_data:
    driver: local
