version: '2'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    environment:
      ELASTICSEARCH_HOSTS: http://xxx.silkrode.com.tw:9200
      elasticsearch.hosts: http://xxx.silkrode.com.tw:9200

    #volumes:
    #  - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"

