version: '3'

# Usage example: https://github.com/stilliard/docker-pure-ftpd/wiki/Docker-stack-with-Wordpress-&-FTP
services:
  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    # remember to replace /folder_on_disk/ with the path to where you want to 
    # store the files on the host machine
    volumes:
      - "./.data/data:/home/username/"
      - "./.data/passwd:/etc/pure-ftpd/passwd"
# uncomment for ssl/tls, see https://github.com/stilliard/docker-pure-ftpd#tls
#      - "/folder_on_disk/ssl:/etc/ssl/private/"
# or ssl/tls with Let's Encrypt (cert and key as two files)
#      - "/etc/letsencrypt/live/<your_server>/cert.pem:/etc/ssl/private/pure-ftpd-cert.pem"
#      - "/etc/letsencrypt/live/<your_server>/privkey.pem:/etc/ssl/private/pure-ftpd-key.pem"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: username
      FTP_USER_PASS: mypass
      FTP_USER_HOME: /home/username
# also for ssl/tls:
#      ADDED_FLAGS: "--tls=2"
    restart: always


# Ref:
#
# https://mileslin.github.io/2020/02/%E4%BD%BF%E7%94%A8-Docker-%E5%BB%BA%E7%BD%AE-FTP-SFTP-%E7%92%B0%E5%A2%83/
# docker run -d --name ftpd_server 
#     -p 23:21 
#     -p 30010-30019:30010-30019 
#     -e "FTP_PASSIVE_PORTS=30010:30019" 
#     -e FTP_USER_HOME=/home/username 
#     -e FTP_USER_NAME=username 
#     -e FTP_USER_PASS=123456 
#     -e "PUBLICHOST=localhost" stilliard/pure-ftpd

