version: '3'
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: atw_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    volumes:
      - ./.data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
  redis:
    image: redis
    ports:
      - 6379:6379

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - EXTERNAL_IP=0.0.0.0
    ports:
      - 28080:80
    depends_on:
        - "mysql"
