version: "3"
services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: casdoor
      MYSQL_USER: user
      MYSQL_PASSWORD: "123456"
    volumes:
      - ./.data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
  # redis:
  #   image: redis
  #   ports:
  #     - 6379:6379
